### ISSUE TITLE
problem with sample.int in sampleOcurrences function

### ISSUE THREAD

**Issue by thm52126** [Farewe/virtualspecies#11]
hello, 

I am trying to generate 250 random species and then use the sampleOcurrences function to generate a list of points for downstream analysis. I can loop through a vector of 250 objects successfully created from the limitDistribution() function. But  then when I attempt to pass through sampleOcurrences, some will generate without error, but I usually get this error which kills my loop:

"Error in sample.int(length(x), size, replace, prob) : 
  too few positive probabilities"

I have tried using lapply() and for loops for this. Additionally, for sampleOcurrences, I make sure replacement = TRUE. 

I would appreciate any suggestions you have regarding this, whether it be an edit to the source code or workaround. Thank you! I really enjoy using virtualspecies!

**Comment by Farewe** [comment]
Dear Thomas,

thank you for reporting this issue. Could you please send the code you used so I can try to reproduce the issue (here or directly on my mail)? Otherwise it is difficult for me to understand what is happening.
