### ISSUE TITLE
Sometimes args are a list, sometimes a vector

### ISSUE THREAD

**Issue by danlwarren** [Farewe/virtualspecies#2]
Not sure if this is intentional, but if so the reason isn't immediately apparent.  When you build a species using generateSpFromFun, the components under the $args are stored in a vector.  When you build a species using generateRandomSp, the args are in a list.  This is invisible and doesn't matter most of the time, but can occasionally cause incredibly cryptic errors.

**Comment by Farewe** [comment]
Thanks for this Dan, I will correct this as soon as possible.

**Comment by Farewe** [comment]
Got this out of my head for quite a while, sorry Dan. This should be corrected now and args should always be a named vector, not a list.
